SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `sourceloggingdaemon`.`tblLogMessages` CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `sourceloggingdaemon`.`tbllogmessages` MODIFY COLUMN `messageType` VARCHAR(45) NOT NULL DEFAULT 'Generic',
 MODIFY COLUMN `userName` VARCHAR(45) DEFAULT NULL,
 MODIFY COLUMN `userSteam` VARCHAR(45) DEFAULT NULL,
 MODIFY COLUMN `userTeam` VARCHAR(45) DEFAULT NULL,
 MODIFY COLUMN `targetName` VARCHAR(45) DEFAULT NULL,
 MODIFY COLUMN `targetSteam` VARCHAR(45) DEFAULT NULL,
 MODIFY COLUMN `targetTeam` VARCHAR(45) DEFAULT NULL,
 MODIFY COLUMN `logLine` TEXT NOT NULL;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
